name: Pull Request Example
on:
  pull_request:
    branches:
      - main
    # ***work ONLY IF changes made to this directory***
    paths:
      - typescript-project/**
  workflow_dispatch:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: typescript-project
    steps:
      - 
        uses: actions/checkout@v2
      - 
        name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm" # This parameter enables caching for package installations, specifically for npm
          cache-dependency-path: typescript-project/yarn.lock
      - 
        name: Install Yarn
        run: npm install --global yarn
      - 
        name: Install dependencies
        run: yarn install --frozen-lockfile
      - 
        name: Run linting
        run: yarn lint
      - 
        name: Build project
        run: yarn build
      - 
        name: Run tests
        run: yarn test
