on:
    schedule:
        - cron: '30 5 * * 1,3'      # Runs at 5:30 AM UTC every Monday (1) and Wednesday (3).
        - cron: '30 5 * * 2,4'      # Runs at 5:30 AM UTC every Tuesday (2) and Thursday (4).

jobs:
    test_schedule:
        runs-on: ubuntu-latest
        steps:
            - 
              name: Not on Mondoy or Wednesday
              if: github.event.schedule != '30 5 * * 1,3'
              run: echo 'Skip this step on Monday and Wednesday.'
            - 
              name: Everytime
              run: echo 'This step will always run.'