name: Context Examples
on: 
    push:
jobs:
    my-context:
        runs-on: ubuntu-latest
        steps:
            - name: My step
              env:
                MY_ACTION: ${{ github.action }}
                ACTION: production
              run: echo "Hello $MY_ACTION, $ACTION"
              
