name: Publish Docker image to Dockerhub
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  push-image-to-dockerhub:
    name: Push Docker image to Dockerhub
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Extract Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/app
      - 
        name: Build and push Docker image
        # Only push the image if not in a pull request
        if: github.event_name != 'pull_request'  
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true  
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - 
        name: Build Docker image (PR)
        # Build the image for pull requests, but do not push
        if: github.event_name == 'pull_request'  
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false  # No push on pull request
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
