name: Build and Push Docker Image to GitHub Container Registry (GHCR)
on:
  push:
    branches: ["release"]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/my-app

jobs:
  build-and-push-docker-image-to-GHCR:
    name: Build and Push Docker Image to GitHub Container Registry (GHCR)
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Permission to read repo content
      packages: write # Permission to write to GitHub Container Registry (GHCR)
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v4
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Extract Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch  # Tag using branch name and commit hash
      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - 
        name: Verify pushed image
        run: |
          echo "Image has been pushed with tags:"
          echo ${{ steps.meta.outputs.tags }}
