name: PostgreSQL Container Service
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:14
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd ./github-actions/pg
          npm install

      - name: Connect to PostgreSQL
        run: node ./github-actions/pg/client.js
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
